import { ArrowHelper, BufferAttribute, Mesh, PerspectiveCamera, Points, Scene, WebGLRenderer, ShaderMaterial, Texture, Clock } from "three";
import { OrbitControls } from '../tools/OrbitControls.js';
import { TorochoidalWave } from "./TorochoidalWave";
export declare class SWSURF {
    scene: Scene;
    renderer: WebGLRenderer;
    camera: PerspectiveCamera;
    clock: Clock;
    controls: OrbitControls;
    dots: Points;
    plane: Mesh;
    sea_floor: Mesh;
    delta: number;
    fps_limit: number;
    waves: Array<TorochoidalWave>;
    maxHeight: number;
    heightmap: Texture;
    noisemap: Texture;
    p_material: ShaderMaterial;
    _Centers: BufferAttribute;
    settings: Object;
    SCALE: number;
    DEPTH_SCALE: number;
    MAX_SCALE: number;
    SPEED: number;
    readonly AMOUNTX: number;
    readonly AMOUNTZ: number;
    readonly CENTERS_NUMBER: number;
    readonly G = 9.81;
    DEBUG_POINT: number;
    arrowHelper: ArrowHelper;
    init(): Promise<void>;
    resetWaves(): void;
    addWave(): void;
    loadHeightMap(): Promise<void>;
    onWindowResize(): void;
    updateDotGrid(): void;
    update(): void;
    render(): void;
}
